# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install activerecord-jdbcmysql-adapter
#
# Configure Using Gemfile
# gem 'activerecord-jdbcmysql-adapter'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: d5e4moc9crif70
  pool: 5
  username: faieddelfwvbws
  password:b1nik29B8sEteGTJAGuJksgvvf

test:
  adapter: postgresql
  encoding: unicode
  database: d5e4moc9crif70
  pool: 5
  username: faieddelfwvbws
  password:b1nik29B8sEteGTJAGuJksgvvf

production:
  adapter: mysql
  database: app_production
  username: root
  password:
  host: localhost
